TOPDIR = ../

include ../definitions.make

OBJECTS = LanguageModel.o \
          SentenceGenerator.o

OBJ = $(patsubst %, objects/%, $(OBJECTS))

LIB = ../Core/libCore.a \
      ../Math/libMath.a \
      ../Features/libFeatures.a

.PHONY: all prepare clean Application libLm.a

all: prepare $(OBJ) libLm.a Application

prepare:
	@mkdir -p objects

$(OBJ): objects/%.o : %.cc %.hh
	$(CC) $(COPTS) -c $< -lcppunit -o $@

libLm.a:
	$(MAKELIB) $(ARFLAGS) $@ $(OBJ)

Application: $(OBJ)
	$(CC) $(COPTS) $@.cc $(OBJ) -Wl,--start-group $(LIB) -Wl,--end-group $(CLIB) -o language-model

clean:
	rm -rf objects/ libLm.a language-model
